// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Students_Portal_App.Data;

#nullable disable

namespace Students_Portal_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Students_Portal_App.Models.Entities.StudentsPaper", b =>
                {
                    b.Property<int>("PaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PaperCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaperDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaperTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PaperId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentsPapers");
                });

            modelBuilder.Entity("Students_Portal_App.Models.Entities.StudentsPortalInfos", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("InTime")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OutTime")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.ToTable("StudentsPortalInfos");
                });

            modelBuilder.Entity("Students_Portal_App.Models.Entities.StudentsPaper", b =>
                {
                    b.HasOne("Students_Portal_App.Models.Entities.StudentsPortalInfos", "Student")
                        .WithMany("Papers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Students_Portal_App.Models.Entities.StudentsPortalInfos", b =>
                {
                    b.Navigation("Papers");
                });
#pragma warning restore 612, 618
        }
    }
}
